version: "3"

services:
  app:
    build: ./web
    volumes:
      - ./web:/web
    ports:
      - 8000:8000
    image: app:django
    container_name: django_container
    command: /bin/bash -c "sleep 10 && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: "django-app-db"
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    volumes:
      - ./data/mysql/db:/var/lib/mysql
