version: "3"

services:
  web:
    build: ./web
    volumes:
      - ./web:/web
    ports:
      - 8000:8000
    image: app:django
    container_name: django_container
    command: "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - .env
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE} 
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    volumes:
      - ./data/mysql/db:/var/lib/mysql
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis:7.2.4-alpine
    expose:
      - 6379
