# Generated by Django 5.0.4 on 2024-04-22 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'booking', 'verbose_name_plural': 'bookings'},
        ),
    ]
